# This is a basic workflow to help you get started with Actions

name: Percy

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
        env:
          GATSBY_DATOCMS_API_TOKEN: ${{ secrets.DATOCMS_API_TOKEN }}
          GATSBY_FORM_SPREE_TOKEN: ${{ secrets.FORMSPREE_TOKEN }}
          GATSBY_DATOCMS_ENVIRONMENT: ${{ secrets.DATOCMS_ENVIRONMENT }}
      - name: Percy Test
        run: yarn add -D @percy/cli && yarn percy snapshot ./public
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
