# This is a basic workflow to help you get started with Actions

name: Percy

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build
        env:
          GATSBY_DATOCMS_API_TOKEN: ${{ secrets.DATOCMS_API_TOKEN }}
          GATSBY_FORM_SPREE_TOKEN: ${{ secrets.FORMSPREE_TOKEN }}
          GATSBY_DATOCMS_ENVIRONMENT: ${{ secrets.DATOCMS_ENVIRONMENT }}

      - name: Percy Test
        run: pnpm add @percy/cli -D && pnpm percy snapshot ./public
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
